---
title: "Analysis"
author: "Alex Tsiofas"
date: "11/02/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
```

```{r}
seq_df <- read.csv("Sequences.csv")

#eliminating the extra column, adding 4 new columns for the A, G, C. T counts
seq_df <- seq_df %>%  select(Name, Sequence) %>% mutate(A_num = NA, G_num = NA, T_num = NA, C_num = NA, GC_content = NA)

for (i in 1:length(seq_df$Sequence)) {
  seq_df$Sequence[i] <- gsub("\\n", "", seq$Sequence[i])
  seq_df$A_num[i] <- nchar(gsub("[GTC]", "", seq_df$Sequence[i]))
  seq_df$G_num[i] <- nchar(gsub("[ATC]", "", seq_df$Sequence[i]))
  seq_df$T_num[i] <- nchar(gsub("[GAC]", "", seq_df$Sequence[i]))
  seq_df$C_num[i] <- nchar(gsub("[ATG]", "", seq_df$Sequence[i]))
}

print(cat(paste("Sequence 1: Borrelia burgdorferi strain QLZP1", seq_df$Sequence[1], 
            "Sequence 2: Borrelia burgdorferi strain CS4", seq_df$Sequence[2], 
            "Sequence 3: Borrelia burgdorferi strain GL18", seq_df$Sequence[3], sep = '\n')))
```
Sequence         | Number of A      | Number of G      | Number of T      | Number of C
-----------------|------------------|------------------|------------------|------------------
`seq_df$Name[1]` | `seq_df$A_Num[1]`| `seq_df$A_Num[1]`| `seq_df$A_Num[1]`| `seq_df$A_Num[1]`
`seq_df$Name[2]` | `seq_df$A_Num[2]`| `seq_df$A_Num[2]`| `seq_df$A_Num[2]`| `seq_df$A_Num[2]`
`seq_df$Name[3]` | `seq_df$A_Num[3]`| `seq_df$A_Num[3]`| `seq_df$A_Num[3]`| `seq_df$A_Num[3]`

```{r}
#calculating percent GC content of each sequence
#for (i in 1:length(seq_df$Sequence)) {
  #seq_df
#}
```

